const express = require("express");
const router = express.Router();
const mainController = require("../controllers/mainController");
router.get("/", mainController.renderMainPage);
router.get("/guest", mainController.renderGuestPage);
router.get("/movie-info", mainController.renderMovieInfoPage);
router.get("/dummy", mainController.renderDummyPage);
router.get("/adminportal", mainController.renderAdminPortalPage);
router.get("/superuserportal", mainController.renderSuperUserPortalPage);
module.exports = router;
